# -*- coding: utf-8 -*-
"""GT_Test_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fF6QxdtCIP_52oIz-dvXP97PiyB-Rgyn

### Modélisation du Problème CSP: SEND + MORE = MONEY

**Objectif**: Affecter un chiffre unique (0-9) à chaque lettre de manière à ce que l'addition soit correcte.

**Variables**:
Les variables du problème sont les lettres uniques présentes dans l'équation:
`S, E, N, D, M, O, R, Y`

Pour modéliser l'addition avec les retenues, nous introduirons également des variables pour les retenues (`C1, C2, C3, C4`), une pour chaque colonne d'addition (de droite à gauche).

**Domaines**:
*   Pour les lettres `S` et `M` (les premières lettres des mots 'SEND' et 'MORE' respectivement), leur domaine est `[1, 2, 3, 4, 5, 6, 7, 8, 9]` car elles ne peuvent pas être zéro (un nombre ne commence pas par 0).
*   Pour toutes les autres lettres `E, N, D, O, R, Y`, leur domaine est `[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]`.
*   Pour les retenues `C1, C2, C3, C4`, leur domaine est `[0, 1]` car l'addition de deux chiffres (plus une retenue potentielle) ne peut générer une retenue supérieure à 1.

**Contraintes**:
Les contraintes sont de plusieurs types:

1.  **Contrainte d'unicité**: Chaque lettre doit représenter un chiffre différent.
    *   `AllDifferent(S, E, N, D, M, O, R, Y)`

2.  **Contraintes arithmétiques** (basées sur l'addition colonne par colonne, de droite à gauche, en incluant les retenues):
    *   **Colonne des unités (D + E)**:
        `D + E = Y + 10 * C1`
    *   **Colonne des dizaines (N + R + C1)**:
        `N + R + C1 = E + 10 * C2`
    *   **Colonne des centaines (E + O + C2)**:
        `E + O + C2 = N + 10 * C3`
    *   **Colonne des milliers (S + M + C3)**:
        `S + M + C3 = O + 10 * C4`
    *   **Colonne des dix milliers (M)**:
        `C4 = M` (la retenue finale est égale à M)

3.  **Contraintes d'initialisation**: Comme mentionné dans les domaines:
    *   `S != 0`
    *   `M != 0`

C'est la modélisation complète du problème SEND + MORE = MONEY en tant que Problème de Satisfaction de Contraintes.
"""

def solve_send_more_money():
    letters = ['S', 'E', 'N', 'D', 'M', 'O', 'R', 'Y']
    solutions = []


    for assignment_values in itertools.permutations(range(10), len(letters)):
        assignment = dict(zip(letters, assignment_values))

        # Contraintes d'initialisation: S et M ne peuvent pas etre 0
        if assignment['S'] == 0 or assignment['M'] == 0:
            continue

        # Extraire les valeurs pour la lisibilite
        S, E, N, D = assignment['S'], assignment['E'], assignment['N'], assignment['D']
        M, O, R, Y = assignment['M'], assignment['O'], assignment['R'], assignment['Y']

        # Verifier les contraintes arithmetiques colonne par colonne, avec gestion des retenues
        # Colonne des unites: D + E = Y + 10 * C1
        sum_DE = D + E
        if sum_DE % 10 != Y:
            continue
        C1 = sum_DE // 10

        # Colonne des dizaines: N + R + C1 = E + 10 * C2
        sum_NRC1 = N + R + C1
        if sum_NRC1 % 10 != E:
            continue
        C2 = sum_NRC1 // 10

        # Colonne des centaines: E + O + C2 = N + 10 * C3
        sum_EOC2 = E + O + C2
        if sum_EOC2 % 10 != N:
            continue
        C3 = sum_EOC2 // 10

        # Colonne des milliers: S + M + C3 = O + 10 * C4
        sum_SMC3 = S + M + C3
        if sum_SMC3 % 10 != O:
            continue
        C4 = sum_SMC3 // 10

        # Colonne des dix milliers: La retenue finale C4 doit etre egale a M
        # (car M est le premier chiffre du résultat 'MONEY' et est la seule retenue possible a ce niveau)
        if C4 != M:
            continue

        # Si toutes les contraintes sont satisfaites, nous avons trouve une solution
        solutions.append(assignment)

    return solutions

import itertools



# Executer le solveur et afficher les resultats
print("Debut de la resolution du probleme SEND + MORE = MONEY...")
money_solutions = solve_send_more_money()

if money_solutions:
    print(f"\n{len(money_solutions)} solution(s) trouvee(s) :")
    for sol in money_solutions:
        print(f"  S={sol['S']}, E={sol['E']}, N={sol['N']}, D={sol['D']}, M={sol['M']}, O={sol['O']}, R={sol['R']}, Y={sol['Y']}")
        print(f"  {sol['S']}{sol['E']}{sol['N']}{sol['D']} + {sol['M']}{sol['O']}{sol['R']}{sol['E']} = {sol['M']}{sol['O']}{sol['N']}{sol['E']}{sol['Y']}")
else:
    print("Aucune solution trouvee.")
print("Recherche terminee.")