# -*- coding: utf-8 -*-
"""GT_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Ut4Qn7MXt-n5gxuDzgDlkj0zlfvfIDV

Programme resolution de CSP

Probleme: colorer 6 provinces (Les 6 provinces de Madagascar)

Modelisation:

Variables: Les 6 provinces(Antananarivo, Toamasina, Mahajanga, Antsiranana, Fianarantsoa, Toliara)

Domaines: 3 couleurs(RGB)

Contraintes:
*   Antananarivo ≠ Toamasina
*   Antananarivo ≠ Mahajanga
*   Antananarivo ≠ Fianarantsoa
*   Antananarivo ≠ Toliara
*   Toamasina ≠ Mahajanga
*   Toamasina ≠ Antsiranana
*   Toamasina ≠ Fianarantsoa
*   Mahajanga ≠ Antsiranana
*   Mahajanga ≠ Toliara
*   Fianarantsoa ≠ Toliara
*   Fianarantsoa ≠ Toamasina
"""

provinces = [
    "Antananarivo",
    "Toamasina",
    "Mahajanga",
    "Fianarantsoa",
    "Toliara",
    "Antsiranana"
]

couleurs = [
    "R",
    "G",
    "B"
]


adjacencies = {
    "Antananarivo": ["Toamasina", "Mahajanga", "Fianarantsoa", "Toliara"],
    "Toamasina": ["Antananarivo", "Mahajanga", "Antsiranana", "Fianarantsoa"],
    "Mahajanga": ["Antananarivo", "Toamasina", "Antsiranana", "Toliara"],
    "Antsiranana": ["Toamasina", "Mahajanga"],
    "Fianarantsoa": ["Antananarivo", "Toamasina", "Toliara"],
    "Toliara": ["Antananarivo", "Mahajanga", "Fianarantsoa"]
}

import itertools

def check_solution(assignment, adjacencies):

    for province, color in assignment.items():
        for neighbor in adjacencies.get(province, []):
            if neighbor in assignment and assignment[neighbor] == color:
                return False
    return True

print("Debut de la recherche de solutions...")
all_possible_assignments = itertools.product(couleurs, repeat=len(provinces))

found_solutions = []
for i, assignment_tuple in enumerate(all_possible_assignments):
    current_assignment = dict(zip(provinces, assignment_tuple))
    if check_solution(current_assignment, adjacencies):
        found_solutions.append(current_assignment)

if found_solutions:
    print(f"\n{len(found_solutions)} solutions trouvees :")
    for i, solution in enumerate(found_solutions):
        print(f"Solution {i+1}:")
        for province, color in solution.items():
            print(f"  {province}: {color}")
else:
    print("Aucune solution trouvee.")

print("Recherche terminee.")